---

- name: check for supported platform
  assert:
    that:
      - ansible_system in ('Darwin', 'Linux', 'Win32NT')
      - zerotier_state in ('present', 'latest', 'absent')

- name: include variables for current system
  include_vars: "{{ ansible_system | lower }}.yml"

- name: run tasks for current system
  include_tasks: "{{ ansible_system | lower }}.yml"
